"""
Screener module models for strategies, signals, and performance tracking.
"""
from sqlalchemy import Column, Integer, String, Numeric, Date, DateTime, Boolean, ForeignKey, Text, Index
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import func
from backend.core.database import Base


class User(Base):
    """User accounts."""
    __tablename__ = 'users'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(50), unique=True, nullable=False)
    email = Column(String(100), unique=True)
    hashed_password = Column(String(255))  # Will be used in Sprint 6
    is_active = Column(Boolean, default=True, nullable=False)
    email_verified = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=False), default=func.now(), nullable=False)


class Strategy(Base):
    """Trading strategies."""
    __tablename__ = 'strategies'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100), unique=True, nullable=False)
    display_name = Column(String(200))
    description = Column(Text)
    python_class = Column(String(200))  # e.g., 'xtumy_v27.XTUMYV27Strategy'
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime(timezone=False), default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=False), default=func.now(), onupdate=func.now())


class StrategyParameter(Base):
    """Strategy parameters per user."""
    __tablename__ = 'strategy_parameters'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey('users.id'), default=1, nullable=False)
    strategy_id = Column(Integer, ForeignKey('strategies.id'), nullable=False)
    parameter_name = Column(String(100), nullable=False)
    parameter_value = Column(JSONB, nullable=False)  # Stores any type: int, float, str, bool
    is_default = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=False), default=func.now(), nullable=False)
    
    __table_args__ = (
        Index('idx_params_user_strategy', 'user_id', 'strategy_id', 'parameter_name', unique=True),
    )


class SignalHistory(Base):
    """Historical signals generated by strategies."""
    __tablename__ = 'signal_history'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey('users.id'), default=1, nullable=False)
    strategy_id = Column(Integer, ForeignKey('strategies.id'), nullable=False)
    symbol = Column(String(20), nullable=False)
    signal_type = Column(String(50), nullable=False)
    signal_date = Column(Date, nullable=False)
    price_at_signal = Column(Numeric(10, 2))
    rsi = Column(Numeric(5, 2))
    adx = Column(Numeric(5, 2))
    signal_metadata = Column('metadata', JSONB)  # Extra signal data (renamed column to avoid SQLAlchemy conflict)
    created_at = Column(DateTime(timezone=False), default=func.now(), nullable=False)
    
    __table_args__ = (
        Index('idx_signals_user_strategy', 'user_id', 'strategy_id', 'signal_date', postgresql_using='btree'),
        Index('idx_signals_unique', 'user_id', 'strategy_id', 'symbol', 'signal_date', 'signal_type', unique=True),
    )


class SignalPerformance(Base):
    """Performance tracking for signals."""
    __tablename__ = 'signal_performance'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, ForeignKey('signal_history.id'), unique=True, nullable=False)
    price_1d = Column(Numeric(10, 2))
    price_3d = Column(Numeric(10, 2))
    price_7d = Column(Numeric(10, 2))
    gain_1d = Column(Numeric(5, 2))
    gain_3d = Column(Numeric(5, 2))
    gain_7d = Column(Numeric(5, 2))
    updated_at = Column(DateTime(timezone=False), default=func.now(), onupdate=func.now())
